# Generated by Django 3.1.7 on 2021-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
