# Generated by Django 3.1.7 on 2021-04-02 01:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210402_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_type', models.CharField(max_length=30)),
                ('session_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=30)),
                ('student_last_name', models.CharField(max_length=30)),
                ('student_username', models.CharField(max_length=30)),
                ('student_password', models.CharField(max_length=30)),
                ('student_address', models.CharField(max_length=30)),
                ('student_gender', models.CharField(max_length=30)),
                ('student_contactno', models.IntegerField(default=0)),
                ('student_emailaddress', models.CharField(max_length=30)),
                ('student_academicLevel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_first_name', models.CharField(max_length=30)),
                ('tutor_last_name', models.CharField(max_length=30)),
                ('tutor_username', models.CharField(max_length=30)),
                ('tutor_password', models.CharField(max_length=30)),
                ('tutor_address', models.CharField(max_length=30)),
                ('tutor_gender', models.CharField(max_length=30)),
                ('tutor_contactno', models.IntegerField(default=0)),
                ('tutor_emailaddress', models.CharField(max_length=30, unique=True)),
                ('tutor_qualification', models.CharField(max_length=30)),
                ('tutor_educationalInstitute', models.CharField(max_length=30)),
                ('tutor_chargePerHour', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=datetime.date(2021, 4, 2))),
                ('session_time', models.TimeField(default=datetime.time(1, 48, 55, 46056))),
                ('session_duration', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.bill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_ratings', models.CharField(max_length=30)),
                ('tutor_review', models.CharField(max_length=30)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_basic.tutor')),
            ],
        ),
    ]
