# Generated by Django 3.1.7 on 2021-04-02 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_bill_ratings_sessions_student_subject_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='session_time',
            field=models.TimeField(default=datetime.time(1, 57, 50, 929614)),
        ),
    ]
