# Generated by Django 3.1.7 on 2021-04-02 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20210402_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='session_time',
            field=models.TimeField(default=datetime.time(1, 59, 6, 956519)),
        ),
    ]
